# This file generates the GitHub Actions matrix.

board:
  - nice_nano

shield:
  - charybdis_left
  - charybdis_right
  - charybdis_dongle
  - settings_reset

format:
  - bt
  - dongle
  - reset

keymap:
  - qwerty

include:
  - board: nice_nano
    shield: charybdis_right
    keymap: qwerty
    snippet: studio-rpc-usb-uart

  # Prospector dongle with xiao_ble board
  - board: xiao_ble
    shield: charybdis_dongle prospector_adapter
    keymap: qwerty
    format: dongle
